CREATE DATABASE FitComDB;

CREATE TABLE FitComDB.Gyms
(GymID VARCHAR(10) NOT NULL, GymName VARCHAR(100) NOT NULL);

CREATE TABLE FitComDB.GymAdministrators
(GymID VARCHAR(10) NOT NULL, Email VARCHAR(254) NOT NULL, password VARCHAR(128) NOT NULL);

CREATE TABLE FitComDB.Trainers
(GymID VARCHAR(10) NOT NULL, Email VARCHAR(254) NOT NULL, password VARCHAR(128) NOT NULL);

CREATE TABLE FitComDB.GymAvailableExercises
(GymID VARCHAR(10) NOT NULL, ExerciseID VARCHAR(10) NOT NULL);

CREATE TABLE FitComDB.Exercises
(ExerciseID VARCHAR(10) NOT NULL);

CREATE TABLE FitComDB.GymMember
(GymID VARCHAR(10) NOT NULL, UserID VARCHAR(10) NOT NULL, UserName VARCHAR(32) NOT NULL, Email VARCHAR(254) NOT NULL);

CREATE TABLE FitComDB.GymMemberAchivements
(UserID VARCHAR(10) NOT NULL, AchivementID VARCHAR(21) NOT NULL, ExerciseID VARCHAR(10) NOT NULL, AchivementDate DATE NOT NULL);

CREATE TABLE FitComDB.AchivementSpecs
(AchivementID VARCHAR(21) NOT NULL, Sets INTEGER NOT NULL, Repeatments INTEGER NOT NULL, WEIGHT DOUBLE NOT NULL);

CREATE TABLE FitComDB.Trainingsplans
(UserID VARCHAR(10) NOT NULL, TrainingsplanID VARCHAR(21) NOT NULL, TrainingsplanTitleID VARCHAR(10) NOT NULL);

CREATE TABLE FitComDB.TrainingsDays
(TrainingsplanID VARCHAR(21) NOT NULL, TrainingsDayID VARCHAR(10) NOT NULL);

CREATE TABLE FitComDB.TrainingsDayExercises
(TrainingsDayID VARCHAR(10) NOT NULL, TrainingsDayExerciseID VARCHAR(21) NOT NULL);

CREATE TABLE FitComDB.TrainingsDayExerciseSets
(TrainingsDayExerciseID VARCHAR(21) NOT NULL, ExerciseID VARCHAR(10) NOT NULL, TrainingsDayExerciseSetID VARCHAR(21) NOT NULL);

CREATE TABLE FitComDB.TrainingsDayExerciseSetGoals
(TrainingsDayExerciseID VARCHAR(21) NOT NULL, Sets INTEGER NOT NULL, Repeatments INTEGER NOT NULL, WEIGHT DOUBLE NOT NULL);